# Uncomment the next line to define a global platform for your project
platform :ios, '12.9'
pod 'SDWebImage','~>5.0'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
pod 'ReachabilitySwift'

target 'sports' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  # Pods for sports
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'
end
